language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: required
notifications:
  on_success:
    - change
  on_failure:
    - change
env:
  global:
    - SC_BUILD_DIR=`pwd`
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.embedpostgresql
    - $HOME/.embedmysql
addons:
  apt:
    packages:
      - graphviz
  sonarcloud:
    organization: "schemacrawler-github"
    token:
      secure: "E/yZtMUKCeEPSOQu8kWNtUZHzp1r9qcBtOVqX3gmjZtIqcOSXopHMzAhl43n9xDg14T1AH0R/fGggXZsxPmgfttkMClZI0GsbTIhZmCg2+ICB7SD9x+JM0QZk3Es7fw8DsjbC8fQZ5EYk6ErvepXPg/YtRAvWQhYp3mQjd2HA84Lp+CAD2hSEydPcLweE7Cs5jQhq5Y+imtV6f7obJ2r2z3D0EILBxi9PrkOAInx0VQEyVniaNOn3cFZ42wtpUKjQbtPxLpT/IGLSh9s3uIv9ANibuZa+TzeDi0HU6Ca96U40OZx5j8h6uVF489o7LH/d7zonwXBiGh3kpTEOPDx6CVSk2TVtuREaXwm4e0uSkBcf6qy1VRh4XszZbjcD7qMF1+ZEeN/7IXxOCSJATD2buq7EhC7Zdbg1kR7GFxUDNoiI5LYDdrWRAXpoaKEszwOgD0WHT7ildGwtdXUcqML5+i/vvSvSt/LDQN/Xe32d0GHMvJQ9HHMtoxL0eCBDncNYE0ih5NzdgaYvAsPEq0wk7VGSIR7W4q7iWalWvD7QqMq8QGdbkZD6QyiEDu4ntx6MhHT7+IcwzOaLL7HbGk0CtBDKkB2hhjDuzeUoVHf1+q+eP6ff2S3TOyDbCMztuCCrUUcuPF61jvsN/I0PspNq7OuB484vfUUj3HN78eTHO8="
script:
  - echo $SC_BUILD_DIR
  - cd "./schemacrawler-parent"
  - mvn -Dcomplete clean install jacoco:report coveralls:report
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - cd $SC_BUILD_DIR
  - git fetch --tags
deploy:
  - provider: releases
    api_key:
      secure: ozkdQjIFJqyzLaX1FNTn/nP+CpuQa9+HoO9pxdMYSNrRn4AWb1WBl37/76QBLBI6ehvRLqPolbz32JxUmyYW/HMuDqI+8vlE2i5iOy5DZHvSayU5U8GwzHg8ibSfXpnEwc2fMmnOEdQeEjnRRU9Aa2k1/8B/MVa6ouF9jjpt+g9tZeXyvitBndD9SlpHb/zlEfiGTjPWHXABBu6K1omWotClbDpr3u5PhljZiCMOwV6gi8FAXTcV9Q/JXp29d9kDlrLUFmAAh6rLaBCAMrum9AnLtEht85YzxZEZAgfnuqHLf77Z65u1J7mLe0rIYXCal1q/Kn2dzg2HXPChvaZqbXFxOQ2V1WoNiyqtYE9tdYIbDAaM3Igzq+WSovrAHil8aBeWXeFdUS+AgQL2yEu/KiV0ggnrviOV6gvVlDRMEbXEg2+rkvX+qeDnlriB/oS8v5sWiPVaVbP6YfBFfmG2VGKsHDdXonG7/id5aLIQ4t9q2IFgKe/qO8hOkZMIMScFkwrPleNpqqo0VvKPmCS07S9cEMqimXkj18Vmh6rMM0w6yt0vjpOT9NjRFWn/MvAGH0dLBO5Jm8z2wFjXggNw3XiglYy8EUxYQunvhJEZOmFtls5g5rSNVfTuZsjoOYOye6DrdtewmB7yzVOGgBaBVUsIr0POxQv+x238rkwfSyo=
    skip_cleanup: true
    on:
      repo: schemacrawler/SchemaCrawler
      branch: master
      tags: true
    file_glob: true
    file:
      - "$SC_BUILD_DIR/schemacrawler-distrib/target/schemacrawler-*-distribution.zip"
      - "$SC_BUILD_DIR/schemacrawler-distrib/target/schemacrawler-*-distribution.zip.SHA-512"
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    verbose: true
    on:
      repo: schemacrawler/SchemaCrawler
      branch: master
      tags: true
    local_dir: "./schemacrawler-distrib/target/_website"
    email: "sualeh@hotmail.com"
    name: "Sualeh Fatehi"
after_script:
  - cd $SC_BUILD_DIR
  - cd "./schemacrawler-parent"
  - mvn sonar:sonar
